package dao;
// Generated Jun 22, 2021 12:30:17 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArticlesApprovisionnement generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "articles_approvisionnement", catalog = "g_stock")
public class ArticlesApprovisionnement implements java.io.Serializable {

	private Integer codeArt;
	private int qteCommande;
	private Date datePrevueLivraison;

	public ArticlesApprovisionnement() {
	}

	public ArticlesApprovisionnement(int qteCommande, Date datePrevueLivraison) {
		this.qteCommande = qteCommande;
		this.datePrevueLivraison = datePrevueLivraison;
	}

	@Id
	@Column(name = "codeArt", unique = true, nullable = false)
	public Integer getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(Integer codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "qteCommande", nullable = false)
	public int getQteCommande() {
		return this.qteCommande;
	}

	public void setQteCommande(int qteCommande) {
		this.qteCommande = qteCommande;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datePrevueLivraison", nullable = false, length = 10)
	public Date getDatePrevueLivraison() {
		return this.datePrevueLivraison;
	}

	public void setDatePrevueLivraison(Date datePrevueLivraison) {
		this.datePrevueLivraison = datePrevueLivraison;
	}

}
